name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Say Hello 
      run: echo "Hello, GitHub practice actions. So fun!"
    - name: configure
      run: ./configure
    - name: make
      run: make
